### ISSUE TITLE
Failing upload

### ISSUE THREAD

**Issue by harababurel** [googleinterns/e2e-search-ml-probing#6]
Command: `node client upload-basic`
Server logs:

```
> node server
listening on 5000
MeasureUploadGoLiveDelay: Login and upload video in normal tab.
AnonymousHome: Click sign in.
anonymous_home.UsernamePrompt: Enter username (email address).
anonymous_home.PasswordPrompt: Enter password.
PersonalHome: Check if 'your videos' is displaying or hidden.
PersonalHome: 'Your videos' not yet showing, click on menu hamburger.
PersonalHome: Click on 'your videos'.
(node:487777) UnhandledPromiseRejectionWarning: TimeoutError: waiting for XPath "//a[@id="endpoint" and @title="Your videos"]//*[contains(text(), "Your videos")]" failed: timeout 30000ms exceeded
    at new WaitTask (/home/sergiup/work/e2e-search-ml-probing/server/node_modules/puppeteer/lib/DOMWorld.js:407:34)
    at DOMWorld._waitForSelectorOrXPath (/home/sergiup/work/e2e-search-ml-probing/server/node_modules/puppeteer/lib/DOMWorld.js:332:26)
    at DOMWorld.waitForXPath (/home/sergiup/work/e2e-search-ml-probing/server/node_modules/puppeteer/lib/DOMWorld.js:318:21)
    at Frame.waitForXPath (/home/sergiup/work/e2e-search-ml-probing/server/node_modules/puppeteer/lib/FrameManager.js:393:51)
    at Frame.<anonymous> (/home/sergiup/work/e2e-search-ml-probing/server/node_modules/puppeteer/lib/helper.js:117:27)
    at Page.waitForXPath (/home/sergiup/work/e2e-search-ml-probing/server/node_modules/puppeteer/lib/Page.js:870:33)
    at Tab.waitForXPath (/home/sergiup/work/e2e-search-ml-probing/server/browser.js:73:36)
    at PersonalHome.clickButtonRaw (/home/sergiup/work/e2e-search-ml-probing/server/page/base.js:121:28)
    at PersonalHome.clickButtonExpectingNav_ (/home/sergiup/work/e2e-search-ml-probing/server/page/base.js:98:9)
    at PersonalHome.clickButton (/home/sergiup/work/e2e-search-ml-probing/server/page/base.js:82:15)
  -- ASYNC --
    at Frame.<anonymous> (/home/sergiup/work/e2e-search-ml-probing/server/node_modules/puppeteer/lib/helper.js:116:19)
    at Page.waitForXPath (/home/sergiup/work/e2e-search-ml-probing/server/node_modules/puppeteer/lib/Page.js:870:33)
    at Tab.waitForXPath (/home/sergiup/work/e2e-search-ml-probing/server/browser.js:73:36)
    at PersonalHome.clickButtonRaw (/home/sergiup/work/e2e-search-ml-probing/server/page/base.js:121:28)
    at PersonalHome.clickButtonExpectingNav_ (/home/sergiup/work/e2e-search-ml-probing/server/page/base.js:98:9)
    at PersonalHome.clickButton (/home/sergiup/work/e2e-search-ml-probing/server/page/base.js:82:15)
    at PersonalHome.goToYourVideos (/home/sergiup/work/e2e-search-ml-probing/server/page/personal_home.js:38:14)
(node:487777) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:487777) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Chromium screenshot:

![screenshot](https://i.imgur.com/tc6Yo5e.png)

**Comment by harababurel** [comment]
Manually created a channel associated to the account and now this step works. However the prober breaks when uploading the video:

![image](https://user-images.githubusercontent.com/8619823/86470321-7d3b9b80-bd3b-11ea-8faf-6a9a8c2786a8.png)

```
> node server
listening on 9001
MeasureUploadGoLiveDelay: Login and upload video in normal tab.
AnonymousHome: Click sign in.
anonymous_home.UsernamePrompt: Enter username (email address).
anonymous_home.PasswordPrompt: Enter password.
PersonalHome: Check if 'your videos' is displaying or hidden.
PersonalHome: 'Your videos' not yet showing, click on menu hamburger.
PersonalHome: Click on 'your videos'.
YourVideos: Doing surprisingly fragile 'click upload button' sequence.
YourVideos:   Fragile sequence successful, rejoyce.
studio_videos.UploadPrompt: Check if the video has been created
studio_videos.UploadPrompt: Actually do the upload!
(node:495428) UnhandledPromiseRejectionWarning: Error: Error on creating the video, check that gen_video.py is working
    at createVideo.then.catch (/home/sergiup/work/e2e-search-ml-probing/server/page/studio_videos.js:182:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:495428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:495428) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:495428) UnhandledPromiseRejectionWarning: Error: /home/sergiup/work/e2e-search-ml-probing/test_videos/wPBkUpe9abLyZxZXvv3N.mp4 does not exist or is not readable
    at Promise.all.filePaths.map (/home/sergiup/work/e2e-search-ml-probing/server/node_modules/puppeteer/lib/JSHandle.js:271:27)
  -- ASYNC --
    at ElementHandle.<anonymous> (/home/sergiup/work/e2e-search-ml-probing/server/node_modules/puppeteer/lib/helper.js:116:19)
    at ChildProcess.python.on (/home/sergiup/work/e2e-search-ml-probing/server/page/studio_videos.js:161:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:495428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```
